language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: quality
      name: "Linting"
      script: npm run lintdsa
    - name: "Security Tests"
      script: npm run security

before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: https://michaelpad.surge.sh
  