language: node_js
node_js:
  - 10

before_deploy:
  - npm run build

jobs:
  include:
    - stage: quality
      name: "Linting"
      script: npm run lint
    - name: "Security Tests"
      script: npm run security
    - stage: deploy
      script: skip
      deploy:
        skip_cleanup: true
        provider: surge
        project: ./dist/
        domain: https://michaelpad.surge.sh
  