# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Linting 
        run: npm run lint
    
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security 
        run: npm run lint
  
  build:
    runs-on: ubuntu-latest
    needs: [linting, security]
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://michaelpad.surge.sh'
          project: './dist/'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - name: Deploy to foo-bar.surge.sh
